"""Mon + Fri 9am: read the sources on X, summarize their market direction, save it, and refresh the site.

Run: /opt/homebrew/bin/python3 -m xoutlook.run [--headed] [--no-publish]
Scheduled by LaunchAgent com.taran.pais-xoutlook (launchd runs a missed slot when the Mac next wakes).
"""
import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timedelta, timezone

from . import config, scrape, summarize

PUBLISH_AGENT = "com.taran.pais-publish"


def window_start(now: datetime, state: dict) -> datetime:
    """Read everything since the last successful run, but never more than MAX_WINDOW_DAYS back."""
    floor = now - timedelta(days=config.MAX_WINDOW_DAYS)
    last = state.get("last_success")
    if not last:
        return floor
    return max(floor, datetime.fromisoformat(last))


def _read_json(path) -> dict:
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}


def _write_json(path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=1))
    tmp.replace(path)


def build_outlook(sources: list[dict], since: datetime, until: datetime, ask=summarize.ask_claude) -> dict:
    total = sum(len(s.get("posts", [])) for s in sources)
    base = {"generated_at": until.isoformat(), "since": since.isoformat(), "until": until.isoformat(),
            "post_count": total, "status": "ok"}
    if total == 0:
        return {**base, "overall": {"bias": None, "summary": "None of the sources posted in this window."},
                "sources": summarize.merge(sources, {"sources": []})}
    reply = ask(summarize.build_prompt(sources, since.isoformat(), until.isoformat()))
    summary = summarize.parse_reply(reply)
    return {**base, "overall": summary["overall"], "sources": summarize.merge(sources, summary)}


def vault_note(o: dict) -> str:
    day = o["until"][:10]
    lines = [f"# X Market Outlook - {day}", "",
             f"Posts from {o['since'][:16].replace('T', ' ')} to {o['until'][:16].replace('T', ' ')} UTC "
             f"({o['post_count']} posts). Generated by PAIS `xoutlook`.", "",
             f"## Overall: {o['overall'].get('bias') or 'n/a'}", "", o["overall"].get("summary", "")]
    for key, label in (("agree", "Agree"), ("disagree", "Disagree")):
        if o["overall"].get(key):
            lines += ["", f"**{label}:** {o['overall'][key]}"]
    for s in o["sources"]:
        lines += ["", f"## {s['name']} (@{s['handle']}): {s.get('bias') or 'n/a'}", ""]
        lines.append(s.get("error") or s.get("summary", ""))
        if s.get("levels"):
            lines.append("- Levels: " + "; ".join(s["levels"]))
        for q in s.get("quotes", []):
            lines.append(f"- \"{q['text']}\" ([post]({q['url']}))")
    return "\n".join(lines) + "\n"


def _save_vault(o: dict) -> None:
    try:
        config.VAULT_DIR.mkdir(parents=True, exist_ok=True)
        (config.VAULT_DIR / f"{o['until'][:10]}.md").write_text(vault_note(o))
    except OSError as exc:  # the site copy is what matters; a vault hiccup shouldn't fail the run
        print(f"[xoutlook] vault note not written: {exc}", file=sys.stderr)


def _publish() -> None:
    subprocess.run(["launchctl", "kickstart", f"gui/{os.getuid()}/{PUBLISH_AGENT}"], check=False, timeout=30)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--headed", action="store_true", help="show the browser window")
    ap.add_argument("--no-publish", action="store_true", help="don't refresh getpais.company afterwards")
    args = ap.parse_args()

    now = datetime.now(timezone.utc).replace(microsecond=0)
    state = _read_json(config.STATE_FILE)
    since = window_start(now, state)
    try:
        sources = scrape.read_sources(since, headless=not args.headed)
        outlook = build_outlook(sources, since, now)
    except Exception as exc:  # noqa: BLE001 - recorded for the site, then re-reported via exit code
        latest = _read_json(config.LATEST_FILE)
        latest["last_attempt"] = {"at": now.isoformat(), "error": f"{type(exc).__name__}: {exc}"}
        _write_json(config.LATEST_FILE, latest)
        print(f"[xoutlook] {now:%F %T} FAILED: {exc}", file=sys.stderr)
        if not args.no_publish:
            _publish()
        return 1

    _write_json(config.DATA_DIR / f"{now:%Y-%m-%d-%H%M}.json", outlook)
    _write_json(config.LATEST_FILE, outlook)
    _write_json(config.STATE_FILE, {"last_success": now.isoformat()})
    _save_vault(outlook)
    print(f"[xoutlook] {now:%F %T} {outlook['post_count']} posts, overall {outlook['overall'].get('bias')}")
    for s in outlook["sources"]:
        print(f"  @{s['handle']}: {s['post_count']} posts, {s.get('bias') or s.get('error') or 'no posts'}")
    if not args.no_publish:
        _publish()
    return 0


if __name__ == "__main__":
    sys.exit(main())
